unbind C-b
set -g prefix C-a
bind C-a send-prefix
bind -n C-Right next-window
bind -n C-Left previous-window
bind c new-window -c "#{pane_current_path}"

set -s escape-time 0

set -g set-titles on
set -g set-titles-string "#T"
# set -g status-bg "#1E1E3F"
set -g status-bg "#323D43"
set -g status-fg white
set -g status on

set -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",*256color:Tc"
set -g default-command /usr/bin/fish
set -g default-shell /usr/bin/fish
